# Configuration ReadTheDocs pour PACS Multi-Systèmes
# Documentation: https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# Build documentation in the docs/ directory with MkDocs
mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
  - epub

# Build environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_checkout:
      # Cancel building pull requests when a new commit is pushed
      - |
        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ]; then
          echo "Cancelling build for external version"
          exit 183
        fi

# Python dependencies required to build the documentation
python:
  install:
    - requirements: docs/requirements.txt
