FROM python:3.11-slim

WORKDIR /app

# Installer les dépendances système
RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    libgdcm-tools \
    dcmtk \
    && rm -rf /var/lib/apt/lists/*

# Copier les requirements
COPY requirements-dicomweb.txt .

# Installer les packages Python
RUN pip install --no-cache-dir -r requirements-dicomweb.txt

# Copier le code de l'application
COPY dicomweb_server/ .

EXPOSE 5000

CMD ["python", "app.py"]
